---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huyg.
--- DateTime: 2019-10-09 14:48
---

--圆周率
function pi()
    return 3.1415
end

--圆的面积
function circle_area(radius)
    return pi()*radius*radius
end